CHANGELOG.md, package.json
Apply changes from `v1.1.x` back to master & bump version to `1.1.1`
=> Updates from release branch

CHANGELOG.md, package.json
Updates for the 1.1.2 release.
=> Release 1.1.2: changelog and package update

package.json, src/OpenSearchResponse.ts, src/components/QueryEditor/MetricAggregationsEditor/styles.ts, src/components/QueryEditor/PPLFormatEditor/OpenCloseButton.tsx, src/components/QueryEditor/QueryEditorRow.tsx, src/components/QueryEditor/QueryTypeEditor/index.tsx, src/components/QueryEditor/SettingsEditorContainer.tsx, src/configuration/DataLinks.tsx, src/datasource.ts, src/dependencies/DataSourcePicker.tsx, src/dependencies/mocks.ts, yarn.lock
In order to fix #28 the dependencies - especially those belonging to `@grafana` - needed to be updated.
I also updated further core dependencies such as react or jest. 
After updating I had some problems with running tests, which were fixed by the changes in jest.config.js.
=> Update `@grafana/data` to 8.5.4

CHANGELOG.md, package.json
=> Release: 2.0.0

pkg/opensearch/client/client.go, pkg/opensearch/client/client_test.go
Backport of https://github.com/grafana/opensearch-datasource/pull/74
=> [1.2.x] Backend: Fix missing custom headers

pkg/opensearch/client/client.go, pkg/opensearch/client/client_test.go
=> [1.2.x] Backend: Fix index being read from the wrong place

src/datasource.ts, src/tracking.ts
Add tracking about executed queries.
=> Tracking: Add query execution tracking

README.md
=> Readme: Fix links to PPL

.github/CODEOWNERS
=> update CODEOWNERS to reflect team name 

src/dependencies/flatten.ts
Nested complex items of arrays views as `[object Object]` string.
This PR improves viewing of all arrays by serialization them to json string.
=> Fix view of nested array field in table column

CHANGELOG.md, package.json
=> prepare release for 2.5.0

CHANGELOG.md, package.json
Includes https://github.com/grafana/opensearch-datasource/pull/168
=> Prepare v2.5.1 release

CHANGELOG.md, cspell.config.json, package.json
* Ability to select order (Desc/Asc) for "raw data" metrics aggregations in https://github.com/grafana/opensearch-datasource/pull/88
* Backend: Set field.Config.DisplayNameFromDS instead of frame.name in https://github.com/grafana/opensearch-datasource/pull/180
=> Prepare v2.6.0

CHANGELOG.md, package.json
* Fix: Take into account raw_data query's Size and Order  by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/210
* Backend: Default to timeField if no field is specified in date histogram aggregation by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/215
* Backend: Change query sort to respect sort order by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/211
* Backend: Add raw_document query support by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/214
=> Prepare v2.8.0

CHANGELOG.md, package.json, yarn.lock
relates to https://github.com/grafana/oss-plugin-partnerships/issues/223
=> Upgrade SDK

CHANGELOG.md, package.json
Releases changes for https://github.com/grafana/opensearch-datasource/pull/259
=> Release 2.11.0

.github/workflows/issue_commands.yml
I just noticed I forgot to make this change for OpenSearch, as was done for the rest of AWS repos, such as https://github.com/grafana/grafana-iot-twinmaker-app/pull/222
=> Use  github app for issue commands workflow

CHANGELOG.md, cspell.config.json, package.json
* Backend refactor and clean by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/283
* Backend: Add trace list query building by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/284
* Migrate to create-plugin and support node 18 by @kevinwcyu in https://github.com/grafana/opensearch-datasource/pull/286
* PPL: Execute Explore PPL Table format queries through the backend by @iwysiu in https://github.com/grafana/opensearch-datasource/pull/289
* Bump semver from 7.3.7 to 7.5.2 by @dependabot in https://github.com/grafana/opensearch-datasource/pull/292
* Bump go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace from 0.37.0 to 0.44.0 by @dependabot in …
=> Prepare v2.14.0 release

CHANGELOG.md, package.json
=> Prepare 2.14.1

CONTRIBUTING.md
Probably while writing the TLS section I accidentally moved "Build a release" to the wrong section
=> Fix: Move "Build a release" in CONTRIBUTING.md out of TLS section

cspell.config.json, src/plugin.json
Add keywords to improve search in the `/connections/add-new-connection` page of Grafana
=> Add keywords

CHANGELOG.md, package.json
Release for:
- #347
- #350
- #353
=> Release 2.14.7

pkg/opensearch/opensearch.go, pkg/opensearch/opensearch_test.go, pkg/opensearch/response_parser.go
Before, if the prefetch error failed, from the user perspective it would return no error and no data. This pr adds error handling for the prefetch error.
Fixes #376 
=> Service Map: Display prefetch error to users

CHANGELOG.md, cspell.config.json, package.json
- Prepares for v2.15.2 release
=> Prepare v2.15.2

CHANGELOG.md, package.json
=> prepare v2.18.0 release

.github/workflows/combine_prs.yml
Fixing the previous PR, which put the workflow in the wrong directory.
=> Add Combine PRs workflow (in the right place)

src/index_pattern.ts, src/opensearchDatasource.test.ts, src/opensearchDatasource.ts
Runs get fields queries through the backend
Fixes #465 
=> Migrate getting fields to the backend

pkg/opensearch/client/client.go, pkg/opensearch/client/index_pattern.go, pkg/opensearch/client/index_pattern_test.go, pkg/opensearch/opensearch.go, src/opensearchDatasource.ts
Implements a separate health check in the backend (instead of just using the resource call). I made it call the backend health check if the toggle is enabled because `testDatasource` call returns the least helpful errors possible when the uses the resource call going through the backend. 
Fixes #468
=> Implement backend health check

CHANGELOG.md, go.mod, go.sum, package.json
Bumps the plugin sdk version to get errorsource improvements
Fixes #
=> Bump grafana-plugin-sdk-go to 0.259.2

CHANGELOG.md, package.json
=> Prepare release 2.22.3

src/components/QueryEditor/BucketAggregationsEditor/utils.ts
See https://github.com/grafana/opensearch-datasource/issues/552
=> Terms aggregation: Change min doc count to 1

CHANGELOG.md, package.json
=> prepare release 2.23.1

.github/pr-commands.json, .github/workflows/pr-commands.yml, cspell.config.json
Adds a workflow for pull requests to add a `pr/external` label for external contributions and also add it to our team board
=> Chore: add label to external contributions

package.json
package.json wasn't updated in the 2.32.2 prepare PR
Fixes #
=> Release 2.32.2

pkg/opensearch/models.go, pkg/opensearch/query_request.go, pkg/opensearch/query_request_test.go
Fixes the name for tracesSize on the backend to connect to the frontend query
Fixes #
=> Fix size option for trace query

src/plugin.json
At some point grafana/awsk-sdk-react was updated that contains the new form elements that aren't supported <10.4.0
Fixes #
=> Update min version of Grafana in plugin.json

.github/workflows/detect-breaking-changes.yml, .github/workflows/e2e-tests.yml, .github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml, cspell.config.json
Fixing warnings according to Zizmor
=> Cleanup github actions files

.github/workflows/detect-breaking-changes.yml, .github/workflows/e2e-tests.yml, .github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml, .github/zizmor.yml
also updated zizmor config and action refs
=> Chore: Add additional permissions for issues and PRs in workflows

.github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml, cspell.config.json
follow up to https://github.com/grafana/opensearch-datasource/pull/625, i forgot to push this commit up to that branch.
=> use get-vault-secrets@main

CHANGELOG.md, cspell.config.json
Want to get `Run query on shift+enter` in 2.25.0 and some actions chores too
=> Update changelog for 2.25.0

CONTRIBUTING.md, docker-compose.yaml
This updates the Contributing guide instructions for local development.
Fixes #
=> Update instructions for local development with Docker

.github/workflows/e2e-tests.yml, .github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml
=> Fix permissions for get-vault-secrets

README.md
Updates the docs to include the required IAM policies for OpenSearch Serverless
Fixes #623
=> Update policies needed for OpenSearch Serverless

CHANGELOG.md, package.json
=> Prepare release 2.28.1

src/components/QueryEditor/PPLQueryEditor/PPLFormatEditor/HelpMessage.tsx
Fixing this one https://github.com/grafana/opensearch-datasource/issues/416 in this feature branch because we rearranged the files a bit so it's different than in main
=> Remove deprecated styles

CHANGELOG.md, package.json
=> Prepare 2.29.0

CHANGELOG.md
=> Update changelog for 2.30.0
