grafana/opensearch-datasource

src/datasource.ts

Slightly improves error handling. the logic to extract the error message is mirroring what is currently being done in the upstream Elasticsearch datasource.
Fixes #6 
cc. @ifrost I also wanted to prefix the error based on the configured "flavor" (OpenSearch / Elasticsearch) but it felt even more confusing in the following situation:
- I have an OpenSearch cluster running
- I set Elasticsearch 7.0.0 in settings
- the error would be "Elasticsearch error: ..." while in fact I'm getting the error from an OpenSearch cluster.
also, I might even not connect at all to an OpenSearch/ES cluster (wrong URL or any network misconfiguration for instance), therefore i'd leave it like it is now, assuming "OpenSearch" in the error message refers to "OpenSearch plugin"

Improve error handling

---

yarn.lock

**What this PR does / why we need it:**
Upgrades the defined frontend packages in the yarn.lock file.
**Special notes for reviewers:**
I created the new `yarn.lock` file by simply deleting the old one and issuing a `yarn install`.

Chore: Upgraded frontend dependencies

---

CHANGELOG.md
package.json
src/plugin.json

**What this PR does / why we need it:**
Release version 1.20 of the OpenSearch datasource plugin containing several dependency updates.

Release: 1.2.0

---

.github/CODEOWNERS
.github/workflows/add-issues-to-project.yml

Added a workflow to move issues to the L&T project for better visibility.
This can not really be tested unless it is on `main`.
Workflow is also in use e.g. here: https://github.com/grafana/grafana-plugin-sdk-python/blob/master/.github/workflows/add-issues-to-project.yml

Tech: Add workflow to automatically move issues to L&T project

---

.github/workflows/add-issues-to-project.yml

The old Github action was not working well. Switching the action to the "official" action/add-to-project from GitHub.

Tech: Changed workflow to automatically move issues to L&T project

---

pkg/opensearch/ppl_handler.go
src/OpenSearchResponse.ts
src/datasource.test.ts
src/datasource.ts

The datasource was using timestamps in local format when requesting a query. That was changed to UTC.
Furthermore the datasource interpreted the receiving timestamps via a PPL query as local timestamps, whereas it should have interpreted them as UTC timestamps.

PPL: Fixed queries being made and interpreted in local timezones

---

src/OpenSearchResponse.ts
src/specs/OpenSearchResponse.test.ts

Backport for https://github.com/grafana/opensearch-datasource/pull/66.
Timestamps in table visualisation were shown as UTC. This PR will convert every property in a dataframe, that is type timestamp or datetime to the local time format.

[1.2.x] PPL: Fix timestamps in `table` visualisation

---

src/OpenSearchResponse.ts
src/specs/OpenSearchResponse.test.ts

Timestamps in `table` visualisation were shown as UTC. This PR will convert every property in a dataframe, that is type `timestamp` or `datetime` to the local time format.

PPL: Fix timestamps in `table` visualisation

---

CHANGELOG.md
package.json
pkg/opensearch/models.go
pkg/opensearch/ppl_handler.go
pkg/opensearch/ppl_response_parser.go
pkg/opensearch/ppl_response_parser_test.go
pkg/opensearch/response_parser.go
pkg/utils/utils.go
src/OpenSearchResponse.ts
src/datasource.test.ts
src/datasource.ts

Release https://github.com/grafana/opensearch-datasource/pull/62 and https://github.com/grafana/opensearch-datasource/pull/61 to OpenSearch in 1.2.1.

Timestamps: Fix timestamp handling and release `1.2.1`

---

CHANGELOG.md
package.json
yarn.lock

Release https://github.com/grafana/opensearch-datasource/pull/62 and https://github.com/grafana/opensearch-datasource/pull/61 to OpenSearch in 2.0.1.

Release: Release version `2.0.1`

---

pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go

As described in https://github.com/grafana/opensearch-datasource/issues/73 custom headers are currently not send when the datasource is in backend mode.
This PR adds a hotfix to add custom headers. Since this will be backported to OpenSearch datasource v1.2.x, I decided to not implement the "full" Grafana HTTP client but rather go with this trivial approach of setting the custom headers.

Backend: Fix missing custom headers

---

pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go

As reported in #78 alert conditions are failing for some users. Reason for this is that the index pattern was read from `DataSourceSettings.Database` but is actually stored at `jsonData.database`.
This PR fixes #78 by also reading the database from `jsonData`.

Backend: Fix index being read from the wrong place

---

config/setupTests.ts
cspell.config.json
pkg/opensearch/client/client.go
src/configuration/OpenSearchDetails.test.tsx
src/configuration/OpenSearchDetails.tsx
src/configuration/mocks.ts
src/datasource.test.ts
src/datasource.ts
src/types.ts
src/utils.ts

**What is this feature?**
This PR adds the possibility to also query OpenSearch Serverless services.
PR in Grafana to add the needed changes: https://github.com/grafana/grafana/pull/60344

Add option to query serverless OpenSearch instances

---

README.md

This PR documents the minimal set of permissions required to use the opensearch datasource with OpenSearch Service and OpenSearch Serverless.
Fixes: #96
Changes:
- Updated references of `Elasticsearch Service` to `OpenSearch Service`
- Add different informational sections on access policies for OpenSearch Service and OpenSearch Serverless
Notes to reviewer:
I tested these permissions the default query for the datasource. I don't know if there are other permissions required depending on the query or some other settings.
References:
- [Identity and Access Management in Amazon OpenSearch Service](https://github.com/grafana/opensearch-datasource/issues/96)
- [Overview of security in Amazon OpenSearch Serverless](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-se …

Docs: add access policies for OpenSearch Service and OpenSearch Serverless

---

src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/MovingAverageSettingsEditor.tsx
src/components/QueryEditor/MetricAggregationsEditor/aggregations.ts

(fixes https://github.com/grafana/opensearch-datasource/issues/98)
when using the `moving_avg` metric, for certain modes there are coefficients (`alpha`, `beta`, `gamma`) that can be configured. the code used `parseInt` to parse them, so when floating-point values are entered (for example `0.35`), it was parsed incorrectly).
also the `MovingAverageEWMAModelSettings` type was defined incorrectly.
how to test:
1. make sure you have an opensearch datasource plugin configured ( read https://github.com/grafana/opensearch-datasource/blob/main/devenv/README.md if unsure)
1. open the opensearch datasource in explore
2. you should see a working "count" metric query
3. add another metric, choose `moving_avg`. configure it:
- `field`: choose `count`
- in `options`, choose `model=holt-winters`
- set …

fix the moving_avg modes

---

src/components/QueryEditor/LuceneQueryEditor/LuceneQueryEditor.test.tsx
src/components/QueryEditor/TracesQueryEditor/TracesQueryEditor.test.tsx
src/components/QueryEditor/TracesQueryEditor/TracesQueryEditor.tsx
src/components/QueryEditor/TracesQueryEditor/formatTraces.ts
src/components/QueryEditor/TracesQueryEditor/traceQueries.ts

Based on a work in progress branch: https://github.com/grafana/opensearch-datasource/pull/122
Adds some basic tests for our work in progress branch to support Trace Analytics:
Once this is merged I think we can close https://github.com/grafana/opensearch-datasource/issues/107

Tests for Traces Query Editor

---

src/QueryBuilder.ts
src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.test.tsx
src/components/QueryEditor/MetricAggregationsEditor/SettingsEditor/index.tsx
src/components/QueryEditor/MetricAggregationsEditor/aggregations.ts
src/components/QueryEditor/MetricAggregationsEditor/utils.ts
src/datasource.ts
src/specs/QueryBuilder.test.ts
src/tracking.ts

1) When we have many indices in elasticsearch with different names of `date` type (not universally @timestamp) field.
2) In some cases we have indices that doesn't contain any `date` type field.
We can't search data for this cases.
1) This PR allows to skip validation for `date` field, and doesn't block adding new datasource.
2) This PR also adds switch option `Use time range` for `raw_data` and `raw_document` search type. This option includes/excludes time range filter and sort in query request for `raw_data` and `raw_document` types only. Default value is enabled.

Add 'Use time range' option, skip date type field validation

---

cspell.config.json
devenv/README.md

This adds instructions to the devenv README for how to set up TLS authentication. This will be useful for testing the changes in https://github.com/grafana/opensearch-datasource/pull/118

Add TLS authentication information in devenv readme

---

README.md
cspell.config.json
devenv/README.md

Adding docs for traces

---

src/datasource.ts
src/traces/formatTraces.test.ts
src/traces/formatTraces.ts

Trace Analytics: Pass datasource type and id in the data link

---

src/components/QueryEditor/index.test.tsx
src/components/QueryEditor/index.tsx

Fixes https://github.com/grafana/opensearch-datasource/issues/137

137 trace analytics hide alias

---

CHANGELOG.md
package.json

Releases:
* Add 'Use time range' option, skip date type field validation by @z0h3 in https://github.com/grafana/opensearch-datasource/pull/125
* Create httpClient with grafana-plugin-sdk-go methods by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/118

Prepare v2.3.0 release

---

src/tracking.ts

Adding tracking for traces. We will be able to add them to our plugin query tracking in [ops.grafana-ops.net](https://ops.grafana-ops.net/d/OpensearchQueryUsage/opensearch-queries-usage-tracking?orgId=1). I didn't separate queries for trace list and for trace details, just returning 'traces'. Does separating them make more sense?

Add query tracking for traces

---

src/configuration/ConfigEditor.test.tsx
src/configuration/OpenSearchDetails.test.tsx
src/configuration/OpenSearchDetails.tsx
src/configuration/utils.ts

Removes the references to the feature flags and adjusts the tests to work with the new defaults
Fixes #170 

Remove references to opensearchDetectVersion flag

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/time_series_query_test.go
pkg/utils/utils.go

* Queries weren't being parsed correctly for the pipeline aggregation field. The same change as this one in Elasticsearch datasource was applied https://github.com/grafana/grafana/pull/60337
* The time vectors are now appended instead of created with nil placeholders the same length as the response buckets. If an entry was missing, then it left the time for that field “nil”. This would run into the following server-side expression error: https://github.com/grafana/grafana/blob/33ba5310ab82c615b158535d869119a8f3c85224/pkg/expr/mathexp/type_series.go#L93-L92 (This should be the same behavior as currently in the Elasticsearch datasource, by the way)
Fixes #154
**Special notes**
I still notice an issue with the time …

Fix backend pipeline aggregation query parsing and data frame building

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

The time series legend when displayed from a backend query (alerting, expressions) was duplicating.
This PR applies a [change from Elasticsearch](https://github.com/grafana/grafana/pull/60169) to generate field names for the value field of time series frames. 
It applies the fixes from [another PR in Elasticsearch ](https://github.com/grafana/grafana/pull/66039) to move from putting the frame name in `frame.name` to `field.Config.DisplayNameFromDS` and getting the metric name from `metric.Field` instead of `metric.ID`. 
The screenshot illustrates the same label for a backend flow and frontend flow. 
Thank you @idastambuk for pointing out where to set the legend.
Fixes #178

Backend: Set field.Config.DisplayNameFromDS instead of frame.name

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

This implements the same changes that were made in Elasticsearch here https://github.com/grafana/grafana/pull/34710 which converts tables to data frames in the function processAggregationDocs (bucketAgg is not "date_histogram").
One of the functions the above PR added also had the following change later applied to it https://github.com/grafana/grafana/pull/64514. It has also been added to this change alongside its test.
Fixes https://github.com/grafana/opensearch-datasource/issues/175
**Testing notes**:
I've created a comparison dashboard between current query flow in the frontend and queries which include a server-side expression which force them through the backend. See the first point …

Backend: Convert tables to data frames

---

src/OpenSearchResponse.ts
src/datasource.test.ts
src/specs/OpenSearchResponse.test.ts
src/types.ts

Datasource query() method in OpenSearch returns LegacyResponseData **for time series queries**, but DataFrames for all other types. 
When LegacyResponseData is returned, Grafana-data eventually calls [toDataFrame](https://github.com/grafana/grafana/blob/12dc56ad0cb5b6b982007d1498346fb03be05f41/packages/grafana-data/src/dataframe/processDataFrame.ts#L309) method in order for viz panels to be able to handle the data. 
This is just doing that already in OpenSearch for time series queries and adjusting tests accordingly. 
The motivation behind doing this now and here is that we will soon start to [migrate response handling logic to the backend](https://github.com/grafana/oss-plugin-partnerships/issues/194) and it will be useful to compare output in DataFrames between FE and Backend, both in …

Refactor PPL and Lucene time series response processing to return DataFrames

---

pkg/opensearch/client/client.go
pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/time_series_query_test.go

This is the equivalent fix that was made in the Elasticsearch data source: https://github.com/grafana/grafana/pull/44027
Thank you for creating such a nice description!
> When doing Data Histogram aggregation `from` and `to` dates are sent as strings. When selected aggregation field has `date` type in Elastic it's automatically converted by Elastic from a string to a number. However, if the aggregation field has a numeric type, such conversion doesn't happen. 
> 
> This automatic type conversion happens inside Elastic because `date` can be represented as [a formatted string or a timestamp in milliseconds or seconds](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html). We always pass both values as timestamps in milliseconds …

Backend: Use int64 type instead of string for from/to date times

---

CHANGELOG.md
package.json

Includes:
* Backend: Convert tables to data frames by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/186
* Refactor PPL and Lucene time series response processing to return DataFrames by @idastambuk in https://github.com/grafana/opensearch-datasource/pull/188
* Backend: Use int64 type instead of string for from/to date times by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/191

Prepare v2.6.2 release

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/time_series_query_test.go

Based on https://github.com/grafana/grafana/pull/60238
In a date_histogram aggregation, the aggregation input a user enters or chooses in the UI is taken into account. Otherwise if none is present, it defaults to the default timeField. 
Contributes to https://github.com/grafana/opensearch-datasource/issues/199
Original issue it fixed would be the equivalent of https://github.com/grafana/grafana/issues/8260

Default to timeField if no field is specified in date histogram aggregation

---

pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go
pkg/opensearch/time_series_query_test.go

Sort is an array, not just a map. 
This PR changes it to an array, which will reflect the order of priority defined in the code. 
The `map[string]interface{}` can also be more precisely typed as `map[string]map[string]string{}`. 
See https://opensearch.org/docs/latest/search-plugins/searching-data/sort/ for documentation on the array and examples.
>The sort parameter is an array, so you can specify multiple field values in the order of their priority.
Sort is only currently used in raw_data (and soon-to-be-implemented-in-the-backend raw_document) queries.
Similar to what was identified in Elasticsearch: https://github.com/grafana/grafana/blob/b39c8aec6c36a9557b147f628496af591cf1583e/pkg/tsdb/elasticsearch/client/search_request.go#L19C1-L19C1
**Which …

Change query sort to respect sort order

---

pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/ppl_handler.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/time_series_query_test.go

* Refactors the client to have types and methods supporting "configured fields" which include the configured timeField and will include the logLevelField for https://github.com/grafana/opensearch-datasource/issues/199. This will minimize the number of lines changed for the upcoming PR.
* Refactors the response parsing in raw_data to resemble the recently-finished raw_document and the similar code in Elasticsearch. There might be some similar code again in https://github.com/grafana/opensearch-datasource/issues/199. Some of this can probably be combined. 
Contributes to #https://github.com/grafana/opensearch-datasource/issues/199

Refactor client to have configuredFields, refactor raw_data response parsing to resemble raw_document

---

CHANGELOG.md
package.json

* Fix template variable interpolation of queries going to the backend by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/220

Prepare v2.8.1

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

* Refactors getTimestamp to return time.Time, not a pointer anymore. This allows it to be included in the generic function to create fields.
* Modifies getTimestamp's behavior a little. If the timestamp string in `fields` is not a valid format (unlikely), it will fall back to check `_source`. Before it would just fail right there. See changes in the test file for the behavior.
* Property names sorting is now extracted out of `processDocsToDataFrameFields`
These functions will be used in the PR for https://github.com/grafana/opensearch-datasource/issues/199, so the intention is to break up the changes to have a more focused review later on.
Contributes to https://github.com/grafana/opensearch-datasource/issues/199

Refactor getTimestamp and sort of property names

---

src/datasource.test.ts
src/datasource.ts

For Lucene queries which were recently migrated to the backend, this fixes ad hoc filters on queries which were redirected to the backend as part of this plugin's [migration to a backend data source](https://github.com/grafana/opensearch-datasource/issues/192).
Ad hoc filters were only added [in the frontend while building the query](https://github.com/grafana/opensearch-datasource/blob/ebbfc716282a66592333a5252ae6453e356ebae7/src/datasource.ts#L648), so this code was not reached when [diverting queries to the backend](https://github.com/grafana/opensearch-datasource/blob/main/src/datasource.ts#L459C1-L484). 
Here is a recording of this PR's behavior:
https://github.com/grafana/opensearch-datasource/assets/4163034/44fd9e81-2897-4176-b322-2482abacda27 …

Add ad hoc filters before sending Lucene queries to backend

---

CHANGELOG.md
package.json

* Add ad hoc filters before sending Lucene queries to backend by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/225
Fixes #224

Prepare v2.8.2 release

---

src/tracking.ts

In [Loki](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/tracking.ts#L161) and [Elasticsearch](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/tracking.ts#L119) we track only non-dashboard queries, as dashboards can have 100s of panels and can have refresh interval of `5s` which leads to huge number of tracked queries.
If we are tracking only Explore/Panel View/Others queries, we can get a better insight into what queries are USERS executing and not which ones are run in dashboards on repeat.
So I decided to create this suggestion PR for you to consider. 🙂

Update trackQuery to track non-dashboard queries

---

jest.config.js
src/QueryBuilder.ts

This fixes an issue where ad-hoc timestamp filters did not work correctly due to the ad-hoc timestamp filter not being translated to a UTC timestamp.
Fixes #212 
Testing instructions are in the original issue's description.
There is an existing test case already in `src/specs/QueryBuilder.test.ts`. It's named `"should return the query with datetime adhoc filter and time range filter"`. No changes required for the actual test case, only update to the jest config to set a predictable timezone was required.

Fix: convert ad-hoc timestamp filters to UTC for PPL queries

---

CHANGELOG.md
cspell.config.json
package.json

Prepares the following additions to the changelog:
- [Explore] Migrate Lucene log queries to the backend by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/228
- The Lucene Logs query type has been refactored to execute through the backend in the **Explore view only**. Existing Lucene Logs queries in Dashboards are unchanged and execute through the frontend. Please report any anomalies observed in Explore by [reporting an issue](https://github.com/grafana/opensearch-datasource/issues/new?assignees=&labels=datasource%2FOpenSearch%2Ctype%2Fbug&projects=&template=bug_report.md).
- Apply ad-hoc filters to PPL queries before sending it to the backend by @kevinwcyu in https://github.com/grafana/opensearch-datasource/pull/244
**Which …

Prepare v2.10.0 release

---

CHANGELOG.md
package.json
pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go
pkg/opensearch/opensearch.go

Similar to the fix in Elasticsearch: https://github.com/grafana/grafana/pull/55172
The http.Client was initialized with every [Lucene](https://github.com/grafana/opensearch-datasource/blob/b2812efd4b20bafbccf0fa3378b96fb57f2f0b43/pkg/opensearch/client/client.go#L323) and [PPL query execution](https://github.com/grafana/opensearch-datasource/blob/b2812efd4b20bafbccf0fa3378b96fb57f2f0b43/pkg/opensearch/client/client.go#L546).
This PR is a refactor so that the http.Client is initialized at a higher level. This Client is passed to the entry point of query execution so that it can be reused. 
Fixes #https://github.com/grafana/opensearch-datasource/issues/250
The following types of …

Reuse http Client in the backend

---

pkg/opensearch/client/client.go
pkg/opensearch/snapshot_tests/lucene_raw_document_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_raw_document.expected_result_generated_snapshot.golden.jsonc
pkg/opensearch/snapshot_tests/testdata/lucene_raw_document.query_input.json
pkg/opensearch/snapshot_tests/testdata/lucene_raw_document.response_from_opensearch.json

Similar to https://github.com/grafana/opensearch-datasource/pull/253 for Lucene raw_data, this PR adds a snapshot test to backend for Lucene raw_document queries. 
Contributes to #255

Backend: Add Lucene raw_document snapshot test

---

CHANGELOG.md
package.json

Release for https://github.com/grafana/opensearch-datasource/pull/263
Update dependencies
prismjs -> 1.28.0
simple-git -> 3.19.1

Release 2.10.2

---

src/datasource.ts

Depends on https://github.com/grafana/grafana/pull/74952 or something similar that actually passes the timeRange to getTagValues to work. (If timeRange isn't passed then nothing changes)
This passes the timeRange of the getTagValue query along to getTerms, so we'll get values in the correct range instead of the default last 6 hours
Fixes #213
This has to be run with a version of main grafana with the above pr merged for the timeRange field to actually be passed in

Get filter values with correct time range

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/time_series_query_test.go

Query building (to OpenSearch) was compared between the backend and the frontend for the following query:
One of the differences observed was: `min_doc_count` was missing from the backend query and present in the frontend query. This PR adds this MinDocCount to the query.
The equivalent fix PR in Elasticsearch was this one: https://github.com/grafana/grafana/pull/59713
Contributes to https://github.com/grafana/opensearch-datasource/issues/197
You can include the changes or cherry-pick this commit to enable backend flow everywhere. https://github.com/grafana/opensearch-datasource/commit/021e747be38330b8906c7c1bbf8beac7bcc3ab60
No difference was observed between this change and the …

Lucene metrics: Parse MinDocCount as int or string

---

pkg/opensearch/client/search_request.go
pkg/opensearch/time_series_query_test.go

Query building (to OpenSearch) was compared between the backend and the frontend for the following query:
One of the differences observed was: `"order":{
"_term":"desc"
},` in the backend query and `"order":{
"_key":"desc"
}` in the frontend query. `_term` was deprecated in Elasticsearch 6.0 and replaced with `_key`. Although this logic was included in an [earlier PR](https://github.com/grafana/opensearch-datasource/pull/5/files#diff-f57eb533f459265bc8c9e1b89d3834a2afcbf36708ca373e643389c7a1c84573R372), I believe that there might have been a omission passing along `opensearch`/`elasticsearch` (flavor) while creating the `aggBuilderImpl` [here](https://github.com/grafana/opensearch-datasource/pull/5/files#diff-f57eb533f459265bc8c9e1b89d3834a2afcbf3670 …

Lucene metrics: Fix replacement of _term to _key in terms order

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/time_series_query_test.go

Query building (to OpenSearch) was compared between the backend and the frontend for the following query:
One of the differences observed was: `"size":500` in the backend query and `"size":0` in the frontend query. This PR sets the `"size":0` in the backend query.
The `"size":500` was incorrectly introduced in https://github.com/grafana/opensearch-datasource/pull/203/files#diff-44afe4fa7a308b985c56a75c710979bd17870768f6365e65baa40115849846e6R79-R80
(Another argument in support of `"size":0` is that in the Elasticsearch datasource, `"size":0` for the same type of query.)
Contributes to https://github.com/grafana/opensearch-datasource/issues/197
You can include the changes or …

Lucene metrics: Remove "size":500 from backend processTimeSeriesQuery

---

CHANGELOG.md
package.json

* Get filter values with correct time range by @iwysiu in https://github.com/grafana/opensearch-datasource/pull/265
* Lucene metrics: Parse MinDocCount as int or string by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/268
* Lucene metrics: Fix replacement of _term to _key in terms order by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/270
* Lucene metrics: Remove "size":500 from backend processTimeSeriesQuery by @fridgepoet in https://github.com/grafana/opensearch-datasource/pull/269

Prepare v2.12.0 release

---

pkg/null/float.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/time_series_query.go
pkg/opensearch/time_series_query_test.go

This PR is a refactor in the backend and should have no impact on the behavior of the data source.
* Removes unused code in the `null` package
* Removes receiver on `parse` method: this makes the code more similar to Elasticsearch, easier to read over while comparing the two code bases.
This was done while working on https://github.com/grafana/opensearch-datasource/issues/197 and tested locally with no noticeable visual difference.

Clean unused code from null, refactor parse method

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/snapshot_tests/lucene_logs_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_logs.query_input.json
pkg/opensearch/time_series_query_test.go

We discovered that [in the frontend](https://github.com/grafana/opensearch-datasource/blob/c4bda8c85a56dc911b42aa8ad3f63079557a9058/src/datasource.ts#L749), Lucene logs queries were built only with `date_histogram` grouping by default time field, no matter what is chosen in the UI.
This fixes the backend to do the same. (This should only affect queries executed in Explore as of [v2.10.0](https://github.com/grafana/opensearch-datasource/releases/tag/v2.10.0).
Contributes to https://github.com/grafana/opensearch-datasource/issues/199

Backend: Fix Lucene logs so it only uses date_histogram

---

pkg/opensearch/client/client.go
pkg/opensearch/client/index_pattern.go
pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/ppl_handler.go
pkg/opensearch/ppl_response_parser.go
pkg/opensearch/response_parser.go
pkg/opensearch/time_series_query.go

- Return error earlier in processQuery
- Replace variable function declarations with just functions: we are not currently replacing these functions and it may be best if we avoided that in the future 
- Export aggContainer: used in a different package for testing this [upcoming PR](https://github.com/grafana/opensearch-datasource/pull/284). I hate to do a change for a test but maybe it is a hint that things are not organized quite right. Or maybe I have not written the test in the right place. I'd like to keep the upcoming PR focused on the feature changes and this kind of change creates unnecessary noise in it. Let me know if we'd prefer it elsewhere!
- Clean unused index in searchRequestBuilder
Preparation while …

Backend refactor and clean

---

pkg/opensearch/ppl_response_parser.go
pkg/opensearch/ppl_response_parser_test.go
pkg/opensearch/response_parser.go
pkg/opensearch/snapshot_tests/ppl_table_test.go
pkg/opensearch/snapshot_tests/testdata/ppl_table.expected_result_generated_snapshot.golden.jsonc
pkg/opensearch/snapshot_tests/testdata/ppl_table.query_input.json
pkg/opensearch/snapshot_tests/testdata/ppl_table.response_from_opensearch.json
src/datasource.test.ts
src/datasource.ts

This make PPL queries with the `table` format run in `Explore` execute on the backend.
You can use a PPL query from the "PPL Table" section [here](https://clouddatasources.grafana.net/goto/vMOq6OmIg?orgId=1) to test it with the external dev.
Fixes #201 
Similar to https://github.com/grafana/opensearch-datasource/pull/259 , in order to test the ad-hoc filters you have to enable ppl queries to be sent from the dashboard to the backend (remove the check for `CoreApp.Explore` in `datasource.ts` at line 548)
Also: my query in `ppl_table.query_input.json` isn't actually the query that produces the response I'm using (i narrowed it down a bit to be smaller) since it seemed like that was …

PPL: Execute Explore PPL Table format queries through the backend

---

src/datasource.ts

While working on https://github.com/grafana/opensearch-datasource/issues/287 I noticed that when I am in the explore tab and make a traces request, the request goes through the backend flow, and when I make a request through the Query Editor it goes through the frontend flow. 
But we haven't actually done the work to support the backend flow for traces yet (that's part of what that ticket is about), so if users attempt to make traces queries in Explore mode they are not going to get data back. 
Until this work is done I think we should add a case to keep just the frontend feature flow going.

Traces bug on Explore

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/opensearch.go
pkg/opensearch/query_request.go
pkg/opensearch/query_request_test.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

While working on adding backend support for traces as part of https://github.com/grafana/opensearch-datasource/issues/287 I noticed that our response parser could use some refactoring improvements. To make the prs easier to read I've broken them up. 
Changes: 
- rename `newTimeSeriesQuery` to `newQueryRequest`. It seems a bit confusing to describe all the work that happens in there as timeSeries queries (although I do think they often---always?-- have a time field attached).
- similarly rename `getTimeSeries` to `parseQuery` I think this more accurately describes what's happening. The request has already been made, the responses just need to be parsed and again I think describing all of the types we support as timeseries feels a bit misleading maybe?
- Pass Datasource Settings in to …

Refactor Response Parser

---

pkg/utils/utils.go
pkg/utils/utils_test.go

The time field for traces can have nanosecond precision. If nanoseconds were used, the following error was shown:
This PR fixes this issue by adapting the timeformat to allow for arbitrary subsecond precision up to nanoseconds. 
N/A
It would be great if this change could be released as a patch release, since I can't use the plugin without this change. Thanks

[BUG] Support time field with nanoseconds

---

CHANGELOG.md
cspell.config.json
package.json

- Support time field with nanoseconds by Christian Norbert Menges <christian.norbert.menges@sap.com> in [#321](https://github.com/grafana/opensearch-datasource/pull/321)
- Refactor tests to remove Enzyme and use react-testing-library in [#319](https://github.com/grafana/opensearch-datasource/pull/319)

Prepare 2.14.2

---

src/plugin.json

This adds suggested `description` and `keywords` values to the opensearch plugin - information on which can be found in the [plugin.json](https://grafana.com/developers/plugin-tools/reference-plugin-json) reference. It improves discoverability of this plugins when a user searches.
Part of https://github.com/grafana/grafana/issues/83447

chore: adds basic description and link to github

---

README.md
src/QueryBuilder.ts
src/datasource.test.ts
src/datasource.ts

Allow to use script in query variable, so that one can use field for simple use case and painless script for advanced use case
Fixes #343

Allow to use script in query variable

---

CHANGELOG.md
cspell.config.json
package.json
pkg/opensearch/client/client.go

After upgrading to version 2.13.0 of the plugin, query from "Explore view" to OpenSearch stopped working. The user used "Forward OAuth" option in datasource configuration to authenticate to OpenSearch.
This passes on the headers to be used to authenticate down stream. 
From @iwysiu's investigation: 
```
Investigation notes for the person who fixes this:
It looks like (unlike the frontend path) the httpclient.Provider we're using for backend queries doesn't automatically forward oauth tokens. We should set ForwardHTTPHeaders on the http options to true and it should be passed. See the [developer notes](https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins#forward-oauth-identity-for-the-l …
```

Bugfix: Forward http headers to enable OAuth for backend queries

---

CHANGELOG.md
package.json

- Annotation Editor: Fix query editor to support new react annotation handling in [#342](https://github.com/grafana/opensearch-datasource/pull/342)

Prepare 2.14.6

---

src/components/QueryEditor/LuceneQueryEditor/LuceneQueryEditor.test.tsx
src/components/QueryEditor/LuceneQueryEditor/LuceneQueryEditor.tsx
src/types.ts

Adds a node graph toggle to the query editor, doesn't do much yet except send over the boolean to the backend. 
Fixes https://github.com/grafana/opensearch-datasource/issues/334
I've done this behind a feature toggle, but did not put the feature toggle into main grafana. We could add it to main grafana if we wanted to but I am not sure it's worth it in this case, it just gives us better typing and things like that. I think it might be enough to just sort of ad-hoc add it as I've done here so that we're able to work on this in multiple prs and merge/release before the full feature is done.

Add node graph toggle

---

pkg/opensearch/response_parser.go
pkg/opensearch/snapshot_tests/testdata/lucene_trace_list.expected_result_generated_snapshot.golden.jsonc
src/datasource.ts
src/utils.test.ts
src/utils.ts

Internal data link configs (data links that link to another data source) were added to the backend in 9.5.0. When Trace queries were added to OpenSearch, it added internal data links in the frontend. When we moved the Trace queries to run on the backend, the data links stopped working in pre 9.5.0 versions of Grafana since the backend response didn't have the internal data link config anymore. This PR adds the logic to populate the internal link config only for Trace List queries and only for the Trace Id field, it should leave all other data link configs untouched.
Fixes #348
For testing, see the contributing doc for instructions on how to set up traces for OpenSearch.

Fix: data links not working in explore for Trace List queries

---

pkg/opensearch/client/client.go
pkg/opensearch/client/index_pattern.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/models.go
pkg/opensearch/ppl_handler.go
pkg/opensearch/ppl_response_parser.go
pkg/opensearch/ppl_response_parser_test.go
pkg/opensearch/query_request.go
pkg/opensearch/query_request_test.go
pkg/opensearch/response_parser.go

Just a small cleanup to eventually make the SG pull request smaller. Looks like a lot but it's mostly renaming 
- uses `client` or `os` instead of `es`, presumably `es` was a remnant of the elastic repo
- typos
- change type of Interval field to time.Duration and convert it only in getMinInterval

Rename ES Client to Client, cleanup 

---

pkg/opensearch/response_parser_test.go
pkg/opensearch/snapshot_tests/lucene_trace_list_test.go
pkg/opensearch/snapshot_tests/lucene_trace_spans_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_trace_list.query_input_multiple.json
pkg/opensearch/snapshot_tests/testdata/lucene_trace_list.response_from_opensearch_multiple.json
pkg/opensearch/snapshot_tests/testdata/lucene_trace_list_and_spans.query_input.json
pkg/opensearch/snapshot_tests/testdata/lucene_trace_spans.query_input_multiple.json
src/components/QueryEditor/LuceneQueryEditor/LuceneQueryEditor.test.tsx
src/components/QueryEditor/LuceneQueryEditor/LuceneQueryEditor.tsx
src/datasource.test.ts
src/datasource.ts
src/types.ts

I think it makes sense for us to redirect all trace queries to the backend before we release the Service Map feature. It's a BE feature and if we don't redirect all trace queries to the BE, we won't have feature parity in Dashboards vs. Explore
I also renamed node graph to Service Map, since it looks like 'service map' is used elswhere (X-ray, Elastic, Tempo) for the feature, and Node Graph is used for the Grafana visualization. 

Traces: Direct all trace queries to the BE and rename Node graph to Service map

---

cspell.config.json
pkg/opensearch/client/models.go
pkg/opensearch/client/models_test.go
pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go

Service Map feature: Add aggregations and query filters to use in service map queries
We're using some new aggregation types (`openSeachQuery.aggs`) and query filters (`openSearchQuery.query`) in requests for service map data to Open search. 
Query filters are what Open Search will filter the documents by, before applying the aggregations to the filtered set. 
**Query filters:** 
- MustNotFilters
- ShouldFilters (functions as OR for conditions inside it)
- Terms/Term filter (they must get marshaled differently depending on whether they have one or multiple values
**Aggregations:** 
- Script aggregation
- Terms aggregation (different than Terms filter) aggregating by term (field) `serviceName`
**Also:**
- tests
- renamed MustQueryBuilder to FilterList, as this struct wasn't Must-specific …

Service Map: Add aggregations and query filters to use in service map queries

---

cspell.config.json
pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/models.go
pkg/opensearch/opensearch.go
pkg/opensearch/opensearch_test.go
pkg/opensearch/query_request.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/snapshot_tests/lucene_service_map_prefetch_test.go
pkg/opensearch/snapshot_tests/lucene_trace_spans_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_service_map_prefetch_input.json

Split the feature into multiple PRs for ease of reviewing. The feature is not enabled by deafult but 'hidden' behind a provisional feature flag. 
In order to get stats for the service map (service info that's displayed inside a node: `avg latency`, `throughput`, `error rate`), we have to build an aggregation query on the `span` indices. The documents (spans) need to be filtered by operationNames and serviceNames, in order to get and aggregate *only* on spans that represent requests from one service to another (not internal processes). 
This reflects how the aggregations are build for the Service Map panel in Open Search. 
To get the operationNames and serviceNames, we have to first query the `service-map` indices and get operations and services from the `serviceName` and …

Service Map: Implement service map index prefetch

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/opensearch_test.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

Due to backend.Responses being a map, we end up getting the services/operations in an inconsistent order when we have multiple responses. This makes some of the tests flaky ([test 1](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/response_parser_test.go#L2667) and [test 2](https://github.com/grafana/opensearch-datasource/blob/8b2f845fe03cd6d9f3c20e42ebd0227552a2a4e4/pkg/opensearch/opensearch_test.go#L39)). One fix for that is just sorting the operations and services (done in this pr), though if we think that's too expensive (I don't think we should have that many of them?) we could also try to rework the tests, though considering that one of them involves checking a big json string that …

Fix flaky tests

---

pkg/opensearch/ppl_handler.go
pkg/opensearch/ppl_response_parser.go
pkg/opensearch/ppl_response_parser_test.go
pkg/opensearch/response_parser.go
src/OpenSearchResponse.ts
src/datasource.test.ts
src/datasource.ts

The code for the backend ppl timeseries actually already matched up pretty well with the frontend (except the field name) and actually had more tests, so this is more of a making-it-a-bit-nicer pr.
Fixes #296 

Backend Migration: migrate ppl timeseries to backend

---

.gitignore
cspell.config.json
pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/models.go
pkg/opensearch/opensearch.go
pkg/opensearch/query_request.go
pkg/opensearch/response_parser.go
pkg/opensearch/snapshot_tests/lucene_service_map_prefetch_test.go
src/tracking.ts

Split the feature into multiple PRs for ease of reviewing. The feature is not enabled by default but 'hidden' behind a provisional feature flag.
After [getting operationNames and serviceNames from the service map prefetch](https://github.com/grafana/opensearch-datasource/pull/362) request, we build the query for getting the stats (throughput, error_rate, avg_latency) for each node (i.e. service). 
This PR implements:
- Detecting the stats query in query_processing.go, and splitting the query in two - one for service map (to get the nodes and edges) and one for stats (latency etc.). They must be split because their aggregations are made on two different sets of filtered documents, so they cannot be combined into one query
- Building the stats query, with filters and aggregations (including …

Service Map: Build Stats request and process responses to dataframes

---

CHANGELOG.md
package.json
src/datasource.test.ts
src/datasource.ts

Seems like switching Lucene and PPL queries to the backend in Dashboards broke some queries (#https://github.com/grafana/opensearch-datasource/issues/389 and https://github.com/grafana/opensearch-datasource/issues/388). Reverting it until we're able to debug and fix the issues.

Revert Lucene and PPL migration to backend

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

Multiple group by terms would only have the final group by term processed and added to the frame when executing on the backend.
This PR updates the way the frame is built up when processing aggregations. If the frame does not have any fields yet, the `propKeys` are added as fields (this will include all of the terms except the final term), otherwise if the frame already has fields, it will use those existing fields.
Fixes #391 
Sending queries to the backend needs to be reenabled for this to work. Change the following condition in `datasource.ts`
```ts
request.targets.every(
(target) =>
target.metrics?.every(
(metric) =>
metric.type === 'raw_data' ||
metric.type === …
```

Fix: Add fields to frame if it does not already exist when grouping by multiple terms

---

.github/workflows/stale.yml

- This PR adds a workflow to mark issues as stale after 1 year of no activity, then closing it 30 days after marked as stale.
- This is the same workflow that is present in grafana/grafana.
- Do we want to try this in some data source repos?

Add Stalebot workflow

---

pkg/opensearch/response_parser.go

Lucene query error responses sometimes have the error message in the `caused_by.reason` property. This handles that case so the user can get a more helpful error message instead of "unknown OpenSearch error response" (see #400)
Fixes #
Use the provisioned "AWS OpenSearch" data source with the following query in Explore. It show the error message shown in the screenshot instead of "unknown OpenSearch error response"

Improve error message by handling caused_by.reason

---

CHANGELOG.md
package.json

Chore: Improve error message by handling `caused_by.reason` error messages in [#401](https://github.com/grafana/opensearch-datasource/pull/401)

Release 2.15.4

---

cspell.config.json
pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go
src/datasource.ts

Elasticsearch multisearch expects the content-type to be `application/x-ndjson` instead of `application/json` ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search-api-desc)) so it causes issues with some reverse proxies. This corrects the content-type.
Fixes #164
based on similar work in elastic https://github.com/grafana/grafana/pull/32282

Use application/x-ndjson content type for multisearch requests

---

pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/opensearch.go
pkg/opensearch/query_request.go
pkg/opensearch/snapshot_tests/lucene_logs_test.go

We had a bug reported in https://github.com/grafana/opensearch-datasource/issues/388#issuecomment-2125144165 where logs queries to ElasticSearch v7.8.1 with OpenSearch plugin were returning No Data. The reason for this was that we're sending "fields" [here](https://github.com/grafana/opensearch-datasource/blob/c8067fcf6c7ed0e30cad4854869286c8ca7f61be/pkg/opensearch/client/search_request.go#L110) to OpenSearch with the timestamp format we desire. 
ElasticSearch api, however, expects `docvalue_fields` instead, so it returns no data. Older versions of Elastic expect `fields` as well. 
There was also some refactoring, since without it, the time field was in some cases added twice in `fields` or `docvalue_fields` (e.g. `docvalue_fields: ["@timestamp", …

Bugfix: Pass docvalue_fields for elasticsearch

---

CHANGELOG.md
package.json

- Bugfix: Pass docvalue_fields for elasticsearch in the backend flow in [#404](https://github.com/grafana/opensearch-datasource/pull/404)
- Use application/x-ndjson content type for multisearch requests in [#403](https://github.com/grafana/opensearch-datasource/pull/403)
- Refactor ad hoc variable processing in [#399](https://github.com/grafana/opensearch-datasource/pull/399)

Prepare 2.16.0

---

CHANGELOG.md
package.json
src/datasource.test.ts
src/datasource.ts

Gradually roll out backend migration with the feature toggle. 
Decided to keep the Explore queries also on backend flow, since that has been enabled for a long while and I didn't want to change functionality. 
Also refactored the tests a bit to reduce repetition. 
Fixes #

Backend migration: Send all queries to backend if openSearchBackendFlow toggle is enabled

---

src/configuration/OpenSearchDetails.test.tsx
src/configuration/OpenSearchDetails.tsx

When serverless is toggled, we should clear the error from getting the server version
Fixes #187 
I also updated the deprecated test functions that were being used while I was in `OpenSearchDetails.test.tsx`. I didn't update the `LegacyForm` imports in `OpenSearchDetails.tsx` because that seemed more risky.

Clear version error when serverless toggled

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/opensearch.go
pkg/opensearch/query_request.go
pkg/opensearch/query_request_test.go
pkg/tsdb/interval.go

Removes the largely unused machinery around interval calculation, both to streamline and to remove a global that could potentially become problematic.
Part of multitenancy work.

chore: refactor interval calculation

---

pkg/opensearch/client/search_request.go
pkg/opensearch/client/search_request_test.go

This changes the timestamp format used in requests for older versions of elasticsearch. The `strict_date_optional_time_nanos` format we're using is not valid for versions < 7.0.
Fixes #417.

fix: use older timestamp format for older elasticsearch

---

src/configuration/OpenSearchDetails.test.tsx
src/configuration/OpenSearchDetails.tsx
src/configuration/utils.ts
src/datasource.test.ts
src/datasource.ts
src/types.ts

This updates the opensearch version detection to determine if its connecting to opensearch in compatibility mode.
Fixes #206 
To run the data prepper (see [CONTRIBUTING.md](https://github.com/grafana/opensearch-datasource/blob/main/CONTRIBUTING.md)) in compatibility mode add the following line to the opensearch environment settings in the jaeger-hotrod docker compose file ([here](https://github.com/opensearch-project/data-prepper/blob/782ad5118c9bb9b6fb752edd5d0914309795f456/examples/jaeger-hotrod/docker-compose.yml#L58)):
`- compatibility.override_main_response_version=true`

Use tagline to detect OpenSearch in compatibility mode

---

CHANGELOG.md
package.json

- Use tagline to detect OpenSearch in compatibility mode in [#419](https://github.com/grafana/opensearch-datasource/pull/419)
- Fix: use older timestamp format for older elasticsearch in [#415](https://github.com/grafana/opensearch-datasource/pull/415)

Prepare v2.17.1 release

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

We currently only add nodes that have stats to the node graph, but we only check whether or not the destination node exists while adding edges. There's a todo in the code about supporting nodes without stats, but checking for source nodes without stats fixes the bug for how the code is currently supposed to work
Fixes #427 

Fix serviceMap when source node doesn't have stats

---

cspell.config.json
lefthook.yml
package.json
yarn.lock

Adds precommit checks:
- frontend lint with --fix
- backend lint with --fix
- spellcheck
with lefthook (https://github.com/evilmartians/lefthook) which we use in main Grafana repo

Chore: Add pre-commit hook

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

- There was [improvement](https://github.com/grafana/grafana/pull/91382) in the UI for Trace View that displays event name more prominently so this adds the "name" as a separate field into the event object
- Improves types (to use Logs and KeyValue types)
- Fixes https://github.com/grafana/opensearch-datasource/issues/434 by adding the event attributes into the fields object
Before (only displaying attribute key values in the title):
After - name displayed at the top + more attributes added to the collapse section:
Fixes https://github.com/grafana/opensearch-datasource/issues/434 

Trace View: Add name and attributes into event object

---

cspell.config.json
pkg/opensearch/client/client.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/opensearch.go
pkg/opensearch/opensearch_test.go
pkg/opensearch/ppl_handler.go
pkg/opensearch/ppl_response_parser.go
pkg/opensearch/ppl_response_parser_test.go
pkg/opensearch/query_request.go
pkg/opensearch/query_request_test.go
pkg/opensearch/response_parser.go

Adds errorsource to the opensearch datasource.
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/1014

Add errorsource to errors

---

pkg/opensearch/opensearch.go
src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

This pr sets up the resource handler (taken from [elasticsearch](https://github.com/grafana/grafana/blob/d1ffcc22d915ab88599c627275cdcf6203e32084/pkg/tsdb/elasticsearch/elasticsearch.go#L190)) and uses it to get the opensearch version
Fixes #

Use resource handler to get version

---

.github/dependabot.yml
cspell.config.json

Right now we have dependabot enabled for security updates. This adds dependabot also for non-security updates just to plugin-sdk-go in open search. The purpose of this is to keep the sdk up to date with the latest observability features for api server: https://github.com/grafana/data-sources/issues/64. This is temporary while decide on our general dependabot process. 
(needs to be enabled in settings once this is merged)
Fixes #
~Converted back to draft since Im not sure if this config will conflict with our already enabled security updates for Dependabot~ confirmed it won't

Add dependabot for updating grafana/plugin-sdk-go

---

.github/combine_prs.yml

Adds the "Combine PRs" action to streamline working with dependabot.

chore: add combine_prs action

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_trace_list.expected_result_generated_snapshot.golden.jsonc

Fixes an issue where some trace groups and last updated values are empty. This causes a panic when parsing the returned trace from OpenSearch into a data frame field.
You can test this by:
1. Clone https://github.com/opensearch-project/opentelemetry-demo and run it with the following
```sh
git clone https://github.com/opensearch-project/opentelemetry-demo.git
cd opentelemetry-demo
docker compose up -d
```
1. Start your local Grafana instance on another port other than 3000
```ini
[server]
http_port = 4000
```
1. Open http://localhost:4000 (use the port you set above) and create an opensearch data source with the following settings …

Fix: handle empty trace group and last updated values

---

pkg/opensearch/opensearch.go
src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

Makes it so that getTerms queries can run through the backend.
Fixes #467 
This is the dashboard I was using to test it. GetTerms is triggered by changing the value for the filter
[opensearch-external-1728336389759.json](https://github.com/user-attachments/files/17284659/opensearch-external-1728336389759.json)

Backend migration: migrate getTerms

---

README.md

The provided provisioning example were incomplete and erroneous.
I merged them (not obivous why log access need different setup) and documented them inline.
This example is proven to be working.
* Improved documentation
* Less frustration during setup
* No reverse-engineering of typescript needed
* Bad / outdated provisioning example

Improve provisioning example in README.md

---

src/opensearchDatasource.test.ts
src/opensearchDatasource.ts
src/types.ts

This migrates the annotation queries to run through the backend, which is required for pdc.
Fixes #466 
This copies the [elasticsearch version of this work](https://github.com/grafana/grafana/pull/68075), including the shortcut of running the queries through the resourcehandler instead of having it run through the query endpoint and parsed on the backend, which would add some work. It also doesn't include work to support variables in the annotation queries that elasticsearch has, but we weren't supporting them to begin with.

Migrate Annotation Queries to run through the backend

---

pkg/opensearch/client/client.go
src/configuration/ConfigEditor.tsx
src/types.ts

Customers have been asking us to support PDC in Opensearch, and now that the backend migration is done, we're finally able to
**Which issue(s) this PR fixes**: #
Fixes #431
You can test it with https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Data_Sources/API_servers/Testing_datasources_with_PDC_Locally
I confirmed it worked by setting it up and seeing it work with the proxy on and seeing queries fail with the proxy off.
It turns out that the [implementation instructions](https://docs.google.com/document/d/1IqYANEnTZ30ENRsWGd-oOf0eM44n8ywfytE4U__JEtQ/edit#heading=h.dix66460452b) for implementing this with the HTTP provider were just using the one from the backend sdk that we're already using.

Add support for PDC

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

When multiple queries are run through the backend flow, it would re-use the same `queryRes` when building the response. This would cause earlier queries' responses to be prepended to subsequent queries' responses. See the next screenshot, where there are 2 queries and both of them have different aliases. In the panel you can see there are 3 series returned and each one is labeled with `alias2`.
With this PR, each query's response is built separately. Here is a screenshot of with the fix. There are now 2 series as expected and they and the alias is set correctly now.
Fixes 

Fix: build each query response separately

---

pkg/opensearch/client/client.go
pkg/opensearch/client/client_test.go

Updates the ppl endpoint to then newer _plugins endpoint.
The _opendistro endpoint was deprecated ([link](https://github.com/opensearch-project/security/issues/3271)) , and opensearch has supported the _plugin endpoint since 1.0.0 ([link](https://opensearch.org/docs/1.0/search-plugins/ppl/endpoint/))
Fixes #499
I decided not to update the frontend query code since we're planning to remove it, but I can if we think it would make sense

Update ppl endpoint for opensearch

---

CHANGELOG.md
package.json
src/opensearchDatasource.ts

Temporarily reverts to using the resource handler for the health check to fix confusing errors while using a wildcard index.
Related to #500 
This is a quick fix for now, and we can revisit making the health check work properly when we have a little more time.

Fix: Revert to using resource handler for health check

---

CHANGELOG.md
package.json
pkg/opensearch/client/client.go

We had a bug report that oauth authorization headers weren't being passed if `Forward OAuth Identity` was selected. Resource requests were passing them fine, but query requests failed. It seems like not passing the context made it so that the appropriate headers weren't being applied [in plugin-sdk](https://github.com/grafana/grafana-plugin-sdk-go/blob/main/backend/http_headers.go#L125). 
User provided us with a docker-compose file where it was clear the the Authorization header was empty: 
After this fix: 
Fixes https://github.com/grafana/opensearch-datasource/issues/487

Pass context in Lucene and PPL query requests

---

pkg/opensearch/client/client.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/ppl_handler.go

We want to deprecate and get rid of `errorsource/httpclient` as a part of https://github.com/grafana/grafana-plugin-sdk-go/issues/1105, as error source middleware implemented in experimental error source httpclient is turning any 400+ response to error and hiding original message. 
Instead of that we have introduced 2 methods developers can use:
- `backend.ErrorSourceFromHTTPStatus` to get error source from http code
- `backend.IsDownstreamHTTPError` to get error source from http error
In this PR we are removing `errorsource/httpclient` and instead just using those methods.

Opensearch: Replace error source http client with a new error source methods

---

src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

This add the LogsVolume feature (See https://grafana.com/developers/plugin-tools/tutorials/build-a-logs-data-source-plugin#show-full-range-logs-volume).
This allow the user to see all logs and not just those displayed in the Logs table view.
Here is a preview of the visualization in the Explore View :
Fixes #352 
Code is mostly adapted from ElasticSearch Plugin + Grafana Logs Datasource plugin documentation. Logs present in the screenshot are linux events from https://github.com/logpai/loghub 
Tests are also adapted from ElasticSearch Plugin, let us know if more tests are required

Add support for logs volumes

---

pkg/opensearch/client/client.go
pkg/opensearch/client/index_pattern.go
pkg/opensearch/client/index_pattern_test.go
pkg/opensearch/opensearch.go

Some errors without errorsource were causing a high SLO burn rate. I added errorsource there and removed errors from a couple of functions that never returned them.
Fixes https://github.com/grafana/data-sources/issues/230

Add error source, remove some impossible errors

---

CHANGELOG.md
CONTRIBUTING.md
docker-compose.yaml
package.json
pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/query_request_test.go

This fixes an issue where the geohash precision isn't respected. This happens because on the backend it's expecting an int, but the query specifies this as a string. So the precision field always ends up being set to the default value of 3 because of the type mismatch. I think this was probably not noticed until the backend migration completed since the previous frontend flow wouldn't have hit the backend path.
Before (it's always 3 characters returned which doesn't match the precision defined in the query):
After:
Fixes #520 
In addition to the actual fix, I updated the docker-compose file to include a new required setting for the opensearch nodes. It requires setting …

fix: parse geohash precision as string instead of int

---

provisioning/datasources/aws-opensearch.yaml

When trying to run `yarn server`, the provisioned opensearch data source wasn't connecting. I needed to update the configuration for the provisioned data source so that it could connect to the opensearch node in docker. You can test by running, `yarn server` then going to the provisioned data source and clicking `Test`. Before this change, it would just error.

Update provisioning to work with docker

---

src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

Similar to https://github.com/grafana/grafana/pull/99356, hidden queries should not be used for supplementary queries.

fix: prevent hidden queries from being used as supplementary queries

---

pkg/opensearch/client/models.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/query_request_test.go
pkg/opensearch/snapshot_tests/lucene_metric_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_metric_sum_group_by_histogram.query_input.json
pkg/opensearch/snapshot_tests/testdata/lucene_metric_sum_group_by_histogram_decimal_interval.query_input.json
pkg/opensearch/snapshot_tests/testdata/lucene_metric_sum_group_by_histogram_invalid_interval.query_input.json

There's a bug when parsing the interval for histogram aggregation. Since it's an input field, it always comes from frontend as string, so in our code it always gets set as default. This adds a parsing function that parses string to float64 and allows decimal numbers

Fix interval parsing

---

src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

Fixes adhoc filters with number fields
Fixes https://github.com/grafana/grafana/issues/99021

Fix adhoc filters with number fields

---

pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go

Trim edges is not working correctly when queries run through the backend flow. There's 2 different issues:
1. The `trimEdges` setting is a string, but is currently getting parsed as an int. This PR casts the setting to an int.
2. The code to delete the data points was skipping data points as it was deleting them so even if the `trimEdges` setting was cast to an int it didn't look like any data points were being trimmed.
Fixes #544 
You can try it out with one of the provisioned data sources. Just set the `Trim Edges` setting to a number that is less than half the total number of data points for the time range you have. With the `Trim Edges` setting, you should see that the number …

Fix: cast trim edges setting from a string to int

---

src/types.ts

https://github.com/grafana/opensearch-datasource/pull/550 was merged with incorrect casing for the frontend options

fix tracesSize casing

---

CHANGELOG.md
package.json

- Remove openSearchBackendFlowEnabled toggle in [#545](https://github.com/grafana/opensearch-datasource/pull/545)
- Make Traces size settable in [#550](https://github.com/grafana/opensearch-datasource/pull/550)
- Bump the all-node-dependencies group across 1 directory with 16 updates in [#560](https://github.com/grafana/opensearch-datasource/pull/560)

Prepare 2.23.0

---

pkg/opensearch/ppl_handler.go

It seems like PPL response errors aren't being forwarded to the user, if the Error object is defined in the response. It has this structure: 
Before:
After:
Fixes #

Forward PPL response errors

---

CHANGELOG.md

- Chore: add label to external contributions in [#567](https://github.com/grafana/opensearch-datasource/pull/566)
- Bump github.com/grafana/grafana-plugin-sdk-go to 0.266.0 in the all-go-dependencies group in [#573](https://github.com/grafana/opensearch-datasource/pull/573)
- Forward PPL response errors in [#581](https://github.com/grafana/opensearch-datasource/pull/581)

Prepare v2.23.2 release

---

src/components/QueryEditor/index.tsx

The placeholder text for query input field for some reason doesn't change even though we're already passing the correct placeholder prop. I tried adding a key, which forces it to update I guess, and it seems like that fixed it. 
Before: 
After:
Fixes #

Bugfix: Fix placeholder text for query string not updating

---

cspell.config.json
docker-compose.yaml
provisioning/dashboards/aws-opensearch.yaml
provisioning/dashboards/aws-opensearch/ecommerce-example.json
provisioning/dashboards/aws-opensearch/traces-example.json
provisioning/dashboards/aws-opensearch/web-traffic-example.json
provisioning/datasources/aws-opensearch.yaml

I tried to recreate some of the visualizations from the sample dashboards from OpenSearch Dashboards.
- Pull the branch
- Run `yarn server`
- Go to http://localhost:5601/app/home#/tutorial_directory and add the sample data

Add sample dashboards

---

src/opensearchDatasource.test.ts
src/opensearchDatasource.ts

As part of the #proj-ds-config-success-improvements we are working on improving our data sources. We are gathering data now and this data source gives us false information about the success because how it returns health check. https://ops.grafana-ops.net/d/ds-health-check-errors/data-sources-health-check-errors?orgId=1&from=now-90d&to=now&timezone=utc&var-grafana_plugins=$__all
This PR fixes that by rejecting the promise when the query returns an error.

Refactor OpenSearchDatasource error handling to use Promise.reject for error cases and update tests accordingly

---

CHANGELOG.md
package.json

- Query Editor: UI improvements and Lucene query type selection improvements in [#583](https://github.com/grafana/opensearch-datasource/pull/583)
- Refactor OpenSearchDatasource error handling to use Promise.reject for error cases and update tests accordingly in [#597](https://github.com/grafana/opensearch-datasource/pull/597)
- Add sample dashboards in [#585](https://github.com/grafana/opensearch-datasource/pull/585)
- Bugfix: Fix placeholder text for query string not updating in [#591](https://github.com/grafana/opensearch-datasource/pull/591)
- Fix size option for trace query in [#589](https://github.com/grafana/opensearch-datasource/pull/589)
- Bump golang.org/x/net from 0.34.0 to 0.36.0 in the go_modules group in [#590](https://github.com/grafana/opensearch-datasource/pull/590)
- …

Prepare 2.24.0

---

pkg/opensearch/client/client.go
src/configuration/OpenSearchDetails.test.tsx
src/configuration/OpenSearchDetails.tsx

Allow PPL to be enabled for AWS OpenSearch serverless collections.
Fixes #604

Allow PPL to be enabled on OpenSearch Serverless

---

CHANGELOG.md
package.json

- Allow PPL to be enabled on OpenSearch Serverless in [#611](https://github.com/grafana/opensearch-datasource/pull/611)
- Update min version of Grafana in plugin.json in [#609](https://github.com/grafana/opensearch-datasource/pull/609)

Prepare 2.25.0

---

src/components/QueryEditor/index.test.tsx
src/components/QueryEditor/index.tsx

Enable `Shift`+`Enter` hotkey to run query
Fixes #615
Hope you are able to accept this! The behaviour is aligned with lots of other data sources including several in core grafana.

Run query on shift+enter

---

pkg/opensearch/lucene_handler.go
pkg/opensearch/query_request_test.go
pkg/opensearch/snapshot_tests/lucene_metric_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_metric_percentiles_group_by_terms_orderby_percentiles.query_input.json
src/QueryBuilder.ts
src/components/QueryEditor/BucketAggregationsEditor/SettingsEditor/index.tsx
src/components/QueryEditor/BucketAggregationsEditor/SettingsEditor/useDescription.ts
src/components/QueryEditor/BucketAggregationsEditor/utils.ts
src/components/QueryEditor/MetricAggregationsEditor/aggregations.ts
src/utils.ts

Fixes https://github.com/grafana/opensearch-datasource/issues/341 where orderBy wasn't correctly displayed in FE and processed in BE. See also https://github.com/grafana/grafana/pull/28910
This 
- displays correct order by options in Terms bucket aggregation
- builds the correct query where metricID is {metricID}[percentage/stat id], for example `1[std_deviation]`
https://github.com/grafana/opensearch-datasource/issues/341
Fixes #

Support ordering by percentiles and extended stats

---

pkg/opensearch/client/models.go
pkg/opensearch/response_parser.go
pkg/opensearch/response_parser_test.go
pkg/opensearch/snapshot_tests/testdata/lucene_logs.expected_result_generated_snapshot.golden.jsonc

Port of https://github.com/grafana/grafana/pull/104117
Together with https://github.com/grafana/grafana/pull/104117 this allows us to see the total logs number.
Fixes #
@idastambuk I was able to assert the total in the response in the browser network tab on the Grafana explorer page. Is there way to point the Grafana image to a recent version that would contain the other PR? I'm not sure how things work out version-wise.

Add total hits to metadata

---

CHANGELOG.md
package.json

- Logs: Add total hits to metadata in [#630](https://github.com/grafana/opensearch-datasource/pull/630)
- Bugfix: Support ordering by percentiles and extended stats in [#627](https://github.com/grafana/opensearch-datasource/pull/627)
- Chore:Update instructions for local development with Docker in [#629](https://github.com/grafana/opensearch-datasource/pull/629)
- Dependencies: Bump the all-go-dependencies group across 1 directory with 2 updates in [#605](https://github.com/grafana/opensearch-datasource/pull/605)
- Dependencies: Bump golang.org/x/net from 0.36.0 to 0.38.0 in the go_modules group in [#608](https://github.com/grafana/opensearch-datasource/pull/608)
- Dependencies: Bump the all-node-dependencies group across 1 directory with 32 updates in …

Prepare 2.26.0

---

CHANGELOG.md
cspell.config.json
package.json

- Bugfix: Add support for Elasticsearch 6.8 by handling hits.total as number by @ranyhb in [#643](https://github.com/grafana/opensearch-datasource/pull/643)
- Bump the all-node-dependencies group across 1 directory with 11 updates in [#644](https://github.com/grafana/opensearch-datasource/pull/644)
- Bump github.com/grafana/grafana-plugin-sdk-go from 0.277.0 to 0.277.1 in the all-go-dependencies group in [#637](https://github.com/grafana/opensearch-datasource/pull/637)

Prepare 2.26.1

---

pkg/opensearch/client/models.go
pkg/opensearch/client/search_request.go
pkg/opensearch/lucene_handler.go
pkg/opensearch/query_request_test.go
src/components/QueryEditor/BucketAggregationsEditor/SettingsEditor/index.tsx
src/components/QueryEditor/BucketAggregationsEditor/aggregations.ts
src/components/QueryEditor/BucketAggregationsEditor/utils.ts

- Updated TermsAggregation model to include an optional execution_hint field.
- Enhanced lucene_handler to handle execution_hint from bucket aggregation settings.
- Modified query_request_test to validate execution_hint functionality.
- Updated BucketAggregationsEditor to include execution hint selection in the UI.
Fixes #

Add execution hint support to terms aggregation

---

CHANGELOG.md
cspell.config.json
package.json

- Add execution hint support to terms aggregation by @enawar-knowunity in [#639](https://github.com/grafana/opensearch-datasource/pull/639)
- Chore: migrate to github actions for publishing in [#652](https://github.com/grafana/opensearch-datasource/pull/652)

Prepare 2.27.0

---

CHANGELOG.md
cspell.config.json

The version numbers were already bumped to 2.28.0 in #675, but a release wasn't actually made. I've just updated the changelog with changes since the previous release.

Release 2.28.0

---

CHANGELOG.md
package.json

- PPL Query Editor: Add modal with sample queries in [#755](https://github.com/grafana/opensearch-datasource/pull/755)
- Dependency updates:
- Bump github.com/grafana/grafana-aws-sdk from 1.1.1 to 1.2.0 in [#776](https://github.com/grafana/opensearch-datasource/pull/776)
- Bump @types/node from 22.17.1 to 22.17.2 in [#766](https://github.com/grafana/opensearch-datasource/pull/766)
- Bump @typescript-eslint/parser from 8.39.1 to 8.40.0 in [#773](https://github.com/grafana/opensearch-datasource/pull/773)
- Bump github.com/grafana/grafana-aws-sdk from 1.1.0 to 1.1.1 in [#761](https://github.com/grafana/opensearch-datasource/pull/761)
- Bump github.com/grafana/grafana-plugin-sdk-go from 0.278.0 to 0.279.0 in [#771](https://github.com/grafana/opensearch-datasource/pull/770)
- Bump …

Prepare 2.30.0
